# Generated by Django 5.0 on 2023-12-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('perfil', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
                ('facultad', models.CharField(max_length=40)),
                ('numeroPortatil', models.CharField(max_length=10)),
                ('fecha', models.CharField(max_length=40)),
                ('observaciones', models.CharField(max_length=100)),
            ],
        ),
    ]
