# Generated by Django 5.0 on 2024-01-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('identificacion', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('correo', models.EmailField(max_length=50)),
                ('perfil', models.CharField(max_length=30)),
                ('facultad', models.CharField(blank=True, max_length=40)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('portatil', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
