# Generated by Django 5.0 on 2023-12-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fecha',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='numeroPortatil',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
